### ISSUE TITLE
回复自定义

### ISSUE THREAD

**Issue by SonderXiaoming** [azmiao/good_morning#5]
感觉一句“早安成功”似乎没什么意思，建议自定义一个词库，随机回复语句。
我自己稍微改了一下，先会随机发送表情包（储存在img文件，有好坏之分），然后根据时间段有不同的随机回复（储存在word）
（此外我多写了个设置，启用后群友都变成美少女）
https://github.com/SonderXiaoming/good_morning
如果需要可以pr

**Comment by azmiao** [comment]
可以的，你直接提交Pr就行，我看到就给你通过

**Comment by azmiao** [comment]
OK
